### ISSUE TITLE
Python-apt 1.8.4 doesnt exist?

### ISSUE THREAD

**Issue by codeclinic** [Sennevds/system_sensors#35]
I just reinstalled this to get the latest version and pip3 is stating that there is no matching distribution for python-apt==1.8.4. I just looked on PyPi and the latest version listed there appears to be 0.7.8.

**Comment by Andoramb** [comment]
same here

**Comment by Andoramb** [comment]
solved by editing the version in _requirements.txt_
Line 5: `python-apt==**1.8.4.1**`

**Comment by codeclinic** [comment]
@Andoramb Thats doersn't really solve the issue, it just loads a different version. When a version is given in the requirements file or manifest it's because that version has some dependency. The real issue is either that the dev set the wrong version number or needs to remove the requirement for that version. 

If you are going to edit the version number yourself, you may as well just delete the version number all together, and just load the latest version of the script.

**Comment by Andoramb** [comment]
That's true... I was just super curious to try it out and works as expected atm on 2 Pis.
Let's see where this goes.
Btw, cool project.

**Comment by Sennevds** [comment]
Hmm will check why the version is wrong

**Comment by OneAmongMany84** [comment]
I'm in a similar boat (re-install); I can apt-get 1.8.4 fine. I tried then commenting out the line in requirements.txt - the rest install but then the system_sensors.py won't run fails at 'import apt' (even though I have 1.8.4.1 already installed).

I also tried making line#5 ==1.8.4.1   - still fails and complains nothing later than 0.7.8. (running pip3 install)

I tried setting line #5 ==0.7.8       -, but "python setup.py egg_info" fails :  
ModuleNotFoundError: No module named 'setuptools'

So I am stuck. :(

**Comment by codeclinic** [comment]
@OneAmongMany84  Did you try installing via python-apt? I've just left updating for now, and so I'm keen to see if python-apt worked for you.

**Comment by OneAmongMany84** [comment]
Hi @codeclinic 

Sorry for my noobness but how would I do that? You mean install the other required packages with apt-get?

I tried just pip install -r requirements and that was fine with python-apt (already at 1.8.4.1...) but broke when importing psutil....   So python3 or python I'm still one package down.

I kind of get the point of python-apt in a scrip but I don't know how I'd use it in bash commands to install anything???

**Comment by OneAmongMany84** [comment]
Update - since I might have had this installed on a Debian Stretch -based system before, I also tried using python 3.5.2  (new install is Buster so Python3.7) - still failing on python-apt and 0.7.8 apparently being the latest....

Trying to work out how this installed so easily last time around?

**Comment by Sennevds** [comment]
Hi everybody sorry for the late answer.
I've just updated the repo. I've removed the requirement and in the install instructions I added the command apt-get install python-apt.

They have changed the way how you need to install the package.
Could you try the new way?

**Comment by OneAmongMany84** [comment]
Hi @Sennevds 

Thank you for stepping in (and thank you again for this tool - once its working its awesome). 

Unfortunately still not working:

"Traceback (most recent call last):
  File "system_sensors.py", line 13, in <module>
    import apt
ModuleNotFoundError: No module named 'apt'"

I had python-apt 1.8.4.1 installed via apt-get already, but (and this is where I hold up my hand for not knowing pyhton at all!) its like python-apt 1.8.4.1 is only available to 'python' not 'python3'  (but when I ran system_sensors.py with 'python'  it complained about something else (psutil) that I couldn't apt-get install).

I had to sudo apt-get install python-apt, so I tried to sudo python3 system_sensors.py - same error. 
I switched to root@  and tried again - it complained about missing psutil, so I ran through the requirements install as root, and still ended up : No module named 'apt'.


Yesterday I actually had a stab at using the code from commit#15 (as that's what I think I had running after you kindly included client_id in the settings.yaml   - no python-apt back then). I actually had some luck with that using python 3.5.2; I could start system_sensors.py with python3, but - just to test in cli- it was laggy AF and after it exited (a looong time from ^C) it showed some traceback errors, loops, some other stuff. My MQTT broker just showed 'config' lines under each sensor. I blitzed it tonight to try your latest update  - I could load it again, but I don;t think you want to be going backwards anyway :)

So yeah how can we make python-apt 1.8.4.1 available to python3  and/or how can you run the .py with python3 and have it use the installed version pf python-apt?

**Comment by Sennevds** [comment]
Hi @OneAmongMany84 no worries I've created the repo so other people could use it and I'm here to help.

Could you try apt-get install python3-apt ?
Whould do you mean with laggy AF? It only sends data every x seconds so if you run it from console you won't see constant updates. CTRL-C is something I know. I need to implement that better but everybody is using it from services so it isn't a real priority.

**Comment by OneAmongMany84** [comment]
Thanks @Sennevds  - that did it:  install python3-apt     :)

What I meant by laggy was I had hit Ctrl-C and nothing....and maybe a minute+ later I'd get a bit of text, finishing out with 
"subprocess.CalledProcessError: Command '['vcgencmd', 'measure_temp']' returned non-zero exit status 255"

(because I'm seeing that even now its working, when I killed my test-run). There was also some stuff about something stuck in a loop. 

....I hot Ctrl-C again....still not exiting.... then eventually it would exit. 

Still looks good. Just need to set up the service again. Thanks again for this - its awesome!

**Comment by Sennevds** [comment]
Okwey good to now the command is working. Ctrl-C is something I know.

**Comment by OneAmongMany84** [comment]
Hmm. My service is not starting:

system_sensor.service - System Sensor service
   Loaded: bad-setting (Reason: Unit system_sensor.service has a bad unit file setting.)
   Active: inactive (dead)

Restart complains of a 'bad unit file setting'. I'm trying to spot my mistake in either the service or settings.yaml.  I don't see it.

I'm running this on dietpi so my paths are /home/dietpi/system_sensors/src/ .py  .yaml
- that's right isn't it? I know the example is a little different (/home/pi/sensors/  ).

I'm also sure I didn't have an issue with the service last time round. Sorry - I'm being the problem child here. :/

**Comment by Sennevds** [comment]
Could you send your service file?

**Comment by OneAmongMany84** [comment]
OK. I'm sorry to say I'm an utter plank and should not be creating service files past 23:00....

I spotted my mistake.....I'd left square brackets on the username.

Service is running now. I'm not getting any values in HA. I'll get on my MQTT browser tonight after work and look at what's not working. Sorry and thanks again!

**Comment by Sennevds** [comment]
No problem mistakes can happen. I'm closing this issue but create a new one if something is still not working!
